name: Build Mihon Panel APK

on:
  workflow_dispatch:   # permite rodar manualmente
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Configurar Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK de release
        run: ./gradlew assembleRelease

      - name: Upload APK assinado
        uses: actions/upload-artifact@v3
        with:
          name: mihon-panel-apk
          path: app/build/outputs/apk/release/*.apk
